name: CI/CD Pipeline for Repo1

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      
      - name: Set Maven Settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: |
            [{
              "id": "github",
              "username": "${{ secrets.GITHUB_ACTOR }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
          options: |
            [{
              "key": "interactiveMode",
              "value": "false"
            }]
      
      - name: Debug settings.xml
        run: cat ~/.m2/settings.xml


      - name: Debug GITHUB_ACTOR and GITHUB_TOKEN
        run: |
          echo "GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}"
          echo "GITHUB_TOKEN is set: $([[ -n "${{ secrets.GITHUB_TOKEN }}" ]] && echo 'Yes' || echo 'No')"


      - name: Build and Test
        run: mvn clean deploy