name: CI/CD Pipeline for Repo1

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      
      - name: Configure Maven Settings for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0'
                        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                        xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd'>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>$GITHUB_ACTOR</username>
                      <password>$GITHUB_TOKEN</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml
          cat ~/.m2/settings.xml

      - name: Debug GITHUB_ACTOR and GITHUB_TOKEN
        run: |
          echo "GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}"
          echo "GITHUB_TOKEN is set: $([[ -n "${{ secrets.GITHUB_TOKEN }}" ]] && echo 'Yes' || echo 'No')"


      - name: Build and Test
        run: mvn clean deploy