name: CI/CD Pipeline for Repo1

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and Test
        run: mvn clean package

      - name: Deploy to Mock Environment
        run: |
          echo "Deploying Repo1 to mock environment..."
          mkdir -p $GITHUB_WORKSPACE/mock/deploy/repo1
          ls -l target  # Debugging: Controleer of het bestand in target aanwezig is
          cp target/repo1-1.0-SNAPSHOT.jar $GITHUB_WORKSPACE/mock/deploy/repo1/
      
      - name: Search for Artifacts
        run: |
          echo "Searching for all .jar files in workspace..."
          find $GITHUB_WORKSPACE -name "*.jar" -print


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mock-deploy-artifacts
          path: $GITHUB_WORKSPACE/mock/deploy/repo1
